exports.mutations = {
    setTenderData: (state, tenderData) => (state.tenderData = tenderData),
    setTenderSector: (state, tenderSector) => (state.tenderSector = tenderSector),
    setTenderType: (state, tenderType) => (state.tenderType = tenderType),
    setTenderCountries: (state, tenderCountry) => (state.tenderCountries = tenderCountry),
    setTenderParams:(state, params) => (state.searchParams = params),
    setTenderEditDialogFlag: (state, flag) => (state.tenderEditDialogState = flag),
    setTenderError: (state, errorObj) => (state.tenderError = errorObj),
    setTenderTitles: (state, tenderTitles) => (state.tenderTitles = tenderTitles),
    setTenderProcurments: (state, tenderProcurments) => (state.tenderProcurments = tenderProcurments),
    setTenderTitlesDict: (state, tenderDict) => (state.tenderDict = tenderDict),
    setTenderFileDialogStateFlag: (state, flag) => (state.tenderFileDialogState = flag),
    setUserPublishedTender: (state, tenders) => (state.publishedUserTender = tenders),
    setClosingDateValueStatus: (state, status) => (state.closingDateValueStatus = status),
}